import capitalize from 'lodash/capitalize.js';
import kebabCase from 'lodash/kebabCase.js';
export {capitalize, kebabCase};

export * from './abbr.js';
export * from './decrypt.js';
export * from './encrypt.js';
export * from './formatPhone.js';
export * from './getStringSize.js';
export * from './isEmail.js';
export * from './isEmptyString.js';
export * from './isEmptyStringLoose.js';
export * from './isPlural.js';
export * from './isSingular.js';
export * from './isString.js';
export * from './lowerFirst.js';
export * from './nl2br.js';
export * from './normalizeEmail.js';
export * from './pascalCase.js';
export * from './plural.js';
export * from './removeInvalidParentheses.js';
export * from './singular.js';
export * from './slugify.js';
export * from './splitFirst.js';
export * from './tokenize.js';
export * from './toString.js';
export * from './upperFirst.js';
