export {capitalize, kebabCase} from 'lodash';

export * from './abbr';
export * from './decrypt';
export * from './encrypt';
export * from './formatPhone';
export * from './getStringSize';
export * from './isEmail';
export * from './isEmptyString';
export * from './isEmptyStringLoose';
export * from './isPlural';
export * from './isSingular';
export * from './isString';
export * from './nl2br';
export * from './normalizeEmail';
export * from './pascalCase';
export * from './plural';
export * from './removeInvalidParentheses';
export * from './singular';
export * from './slugify';
export * from './tokenize';
export * from './toString';
export * from './upperFirst';
